apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro-svc-seeding
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: ./
    repoURL: https://github.com/sinhasonalkumar/applications-in-argocd.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true